# SITE CONFIGURATION
title: 黄浦童军 # your site title
author: adevil # You :P
description: > # Meta description of Homepage
  一个国际性的、非政治性的、非军事性的、非政府性的（NGO）以及非营利性的（NPO）的青少年运动组织
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://hpscout.cn" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: adevil
  links:
    - https://github.com/adevil

# THEME SETTINGS
navigation: # Navigation links
  - {name: '首页', link: '/'}
  - {name: '关于', link: '/about'}
#  - {name: 'Contact', link: '/contact'}

tagline: >
  一个国际性的、非政治性的、非军事性的、非政府性的（NGO）以及非营利性的（NPO）的青少年运动组织

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: adevil23@gmail.com # email for form submission

#twitter_username: adevil23 # replace with your_twitter_username or comment to remove link from footer
github_username:  adevil # replace with your_github_username or comment to remove link from footer
#instagram_username: adevil23 # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: adevil23 # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
